### ISSUE TITLE
Error in Account_Check file for App Connect Flow Process

### ISSUE THREAD

**Issue by NgwanaTau** [IBM/microservices-using-apiconnect-and-appconnect#16]
Hi

Thanks for the work put into this tutorial, was great to learn from it. I just wanted to point out an issue that I believe you could rectify or just point it out on the step-by-step tutorial.

In line 9 of the Account_Check.json file in the App Connect folder, the host has been specified as "localhost:32625". This should instead be specified as <cluster-ip>:<account-service-nodeport>. 

Hope that helps.

**Comment by muralidharchavan** [comment]
Hi @NgwanaTau Thanks for the feedback. The hostname in the Account_Check.json file will be overwritten with the microservices hostname and port in the app connect API configurations. However, since it doesn't make sense for localhost to be there in any case, I have updated the urls.
