### ISSUE TITLE
not able to install mongodb

### ISSUE THREAD

**Issue by awsiotdemo** [IBM/microservices-using-apiconnect-and-appconnect#21]
Hi I am getting error while installing mongodb using command cd mongodb

**Comment by maheshwarishikha** [comment]
@awsiotdemo  if you have cloned the repo then you must have got the `mongodb` directory in it. 
`cd mongodb` - is the command just to change the directory. You need to change directory to the cloned repo first and then to mongodb.
Please retry and let me know if it helps. Thanks.

**Comment by awsiotdemo** [comment]
Thanks for the suggestions. I am into Mongodb directory but when I am deploying mongodb from yaml file I am getting following error  - 

error validating data: apiVersion not set; if you choose to ignore these errors, turn validation off with --validate=false


YAML Original Code - 

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mongo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: mongo
        version: v1
    spec:
      containers:
        - image: mongo
          name: mongo
          ports:
            - containerPort: 27017
              name: mongocontainer
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  type: NodePort
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    name: mongo

Is there anything which I need to change

**Comment by maheshwarishikha** [comment]
Thanks @awsiotdemo !! It is causing because of kubectl version. In newer version of Kubernetes 1.16 onwards, apiVersion extensions/v1beta1 has been deprecated and need to use apps/v1 and some more changes because of this.

I have made code changes now. Kindly get the latest code and try again. Let me know if it works for you now. Thanks.

**Comment by maheshwarishikha** [comment]
@awsiotdemo - hope it have worked for you. Closing this issue because of no-activity from a long time. Please feel free to reopen or open new issue if required. Thanks.
